### ISSUE TITLE
没办法断点调试

### ISSUE THREAD

**Issue by kevintianyao** [luokeluo/objc4#1]
大佬，你好，我下了这个demo，可以跑起来，main里边的log日志也打印出来了，但是我想debug，打断点，没反应，不知道怎么回事

**Comment by kevintianyao** [comment]
> 大佬，你好，我下了这个demo，可以跑起来，main里边的log日志也打印出来了，但是我想debug，打断点，没反应，不知道怎么回事


知道了，在build phases 里需要把main文件放到最前边就可以了

**Comment by luokeluo** [comment]
不好意思，最近忙没回您，做法是对的
